### ISSUE TITLE
[].mean? :map がArray#map に飛ぶ

### ISSUE THREAD

**Issue by scivola** [hibariya/ruremai#7]
`[].mean? :map` が Enumerable#map でなく Array#map に飛ぶようです。

**Comment by hibariya** [comment]
@scivola 教えてくださってありがとうございます。確かにおかしな動きをしていたので、

1. るりまの新しい URL を使うようようにする
2. Method#owner の ancestors もみるようにする

という対応をしてみました (バージョン 0.0.5 で publish しています) 🚀
